"""PDF design report generation using fpdf2."""

from fpdf import FPDF


def generate_pdf(result: dict, output_path: str = "pfc_design_report.pdf"):
    """Generate a single-page PDF design report.

    Args:
        result: output of SystemAnalyzer.analyze()
        output_path: path for the PDF file
    """
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=False)

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "PFC Design Report", ln=True, align="C")
    pdf.ln(5)

    spec = result["spec"]
    design = result["inductor_design"]

    # Specifications
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Specifications", ln=True)
    pdf.set_font("Helvetica", "", 10)
    specs = [
        f"Input: {spec.vin_min}-{spec.vin_max} Vrms, {spec.f_line}Hz",
        f"Output: {spec.vout} Vdc, {spec.pout_total/1000:.1f} kW",
        f"Topology: {spec.n_phases}-phase interleaved PFC, fsw={spec.fsw/1000:.0f}kHz",
    ]
    for s in specs:
        pdf.cell(0, 5, "  " + s, ln=True)
    pdf.ln(3)

    # Inductor
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Inductor Design", ln=True)
    pdf.set_font("Helvetica", "", 10)
    ind_lines = [
        f"Core: {design.core.part_number} ({design.core.material}) x{design.n_cores}",
        f"Turns: {design.n_turns}, Wire: {design.wire_d_mm}mm x{design.n_parallel}",
        f"L_target: {design.L_target_uh:.0f}uH, L_noload: {design.L_noload_uh:.0f}uH",
        f"L_eff @ Ipk: {design.L_eff_at_ipeak_uh:.0f}uH, Window fill: {design.kw*100:.0f}%",
    ]
    for line in ind_lines:
        pdf.cell(0, 5, "  " + line, ln=True)
    pdf.ln(3)

    # Loss breakdown
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Loss Breakdown", ln=True)
    pdf.set_font("Helvetica", "", 10)

    total = result["total_loss"]
    for name, val in result["breakdown"].items():
        if val > 0.5:
            pct = val / total * 100 if total > 0 else 0
            pdf.cell(0, 5, f"  {name}: {val:.1f}W ({pct:.1f}%)", ln=True)

    pdf.ln(3)
    pdf.cell(0, 5, f"  Total Loss: {total:.1f}W", ln=True)
    pdf.cell(0, 5, f"  Efficiency: {result['efficiency']*100:.2f}%", ln=True)
    pdf.ln(5)

    # Footer
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 5, "Generated by pfc_design calculator", ln=True, align="C")

    pdf.output(output_path)
    return output_path
